### PR TITLE
Maven project creation

### PR DESCRIPTION
**Pull request by hrgdavor**
added a pom.xml and updated the build.xml script. Both now work fine. build.xml now generates files to folder: target like maven does.

### CODE REVIEW

**Comment by ClickerMonkey** [comment]
I added the .classpath file back for the sake of Eclipse users, I spent way to much time trying to get that fixed when I first imported your branch of the project.

**Comment by ClickerMonkey** [comment]
Was your goal to get this project published to Maven Central? Looks like you can't get GitHub projects to Maven Central without creating your project somewhere else as well. Do you have any experience/knowledge with this?

**Comment by hrgdavor** [comment]
Hope it is not complicated. But no, I have no exp with publishing to maven
central.

**Comment by hrgdavor** [comment]
Hi,

I have no experience with it, so I googled a bit,
you might have seen this one, but here it is
http://www.sonatype.org/nexus/2015/01/08/deploy-to-maven-central-repository/
maybe it helps :)

I have a small utility lib of my own that I would like to push to maven
central,
so I will also try to set it up. If you gather some more useful info, let
me know :)

https://github.com/hrgdavor/java-watcher

**Comment by hrgdavor** [comment]
I am now in proces of doing the steps to open a project at sonatype,
but I think that does not mean that it must move from github, it just has
to be registered
there to be allowed to publish to their repo, and they sync it then with
maven central.

Issue #1 that I resolved with them quickly:
my groupId was org.hrg but that is not allowed with them if I am not the
owner of the domain in reverse (hrg.org)

One option is then to use com.github.username ...
Since I have the domain hrg.hr I decided to use that and they asked me to
setup a redirect page on that domain...
 ... and then they confirmed it after I created a simple redirect url
http://pub.hrg.hr/java-watcher.

Now sonatype will prepare the staging area for the project in few days.

Davor Hrg

**Comment by hrgdavor** [comment]
Hi,

I was able to deploy my first release !! :) :) :) wooot

http://repo1.maven.org/maven2/hr/hrg/java-watcher/0.1.0/

**Pull request merged**
